### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by christiandennis** [antham/yogo#47]
Hi, I tried running the show email but I'm getting segmentation fault. 

```
./yogo_darwin_amd64 inbox show some-email 1
---
From  : <>
Title :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13aa308]

goroutine 1 [running]:
github.com/antham/yogo/cmd.renderMail(0xc00001e4b0)
	/home/circleci/gommit/cmd/inbox_view.go:63 +0x218
github.com/antham/yogo/cmd.glob..func7(0x17f41a0, 0xc000282400, 0x2, 0x2)
	/home/circleci/gommit/cmd/inbox_show.go:31 +0x108
github.com/spf13/cobra.(*Command).execute(0x17f41a0, 0xc0002823a0, 0x2, 0x2, 0x17f41a0, 0xc0002823a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17f3480, 0x18240e8, 0x1476264, 0x4)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/antham/yogo/cmd.Execute()
	/home/circleci/gommit/cmd/root.go:38 +0x92
main.main()
	/home/circleci/gommit/main.go:6 +0x20
```

The inbox list is working perfectly tho!

**Comment by christiandennis** [comment]
closing this. i can use the --json flag just fine :)
